somedia/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('somediaapp.urls', namespace='somedia')),
    url(r'^', include('social.apps.django_app.urls', namespace='social')),
]

admin.site.site_header = 'Somedia'

somediaapp/urls.py
__author__ = 'njerucyrus'
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^create-account/', views.create_account, name='create_account'),
    url(r'^post_tweet/(?P<product_id>[0-9])/$', views.post_tweet, name='post_tweet'),
    url(r'^add-product/$', views.add_product, name='add_product'),
    url(r'^my-products/$', views.display_my_products, name='my_products'),
    url(r'^analyse-tweet/(?P<product_id>[0-9])/$', views.analyse_product_tweet, name='analyse_product_tweet'),
    url(r'^stats/(?P<id>[0-9])/$', views.tweet_analysis, name='stats'),

]

somediaapp/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User


class UserProfile(models.Model):
    user = models.OneToOneField(User, )
    business_name = models.CharField(max_length=64, blank=True, null=True)

    def __unicode__(self):
        return str(self.user)


class Product(models.Model):
    profile = models.ForeignKey(UserProfile, )
    product_name = models.CharField(max_length=32, )
    tweet_id = models.CharField(max_length=128, null=True, blank=True)
    tweet = models.TextField(max_length=140, null=False)

    def __unicode__(self):
        return self.product_name


class TweetReply(models.Model):
    product = models.ForeignKey(Product, )
    reply = models.CharField(max_length=140, null=True, blank=True)
    latitude = models.DecimalField(max_digits=64, decimal_places=10)
    longitude = models.DecimalField(max_digits=64, decimal_places=10)
    latitude = models.DecimalField(max_digits=64, decimal_places=10, null=True, )
    longitude = models.DecimalField(max_digits=64, decimal_places=10, null=True, )
    status = models.CharField(max_length=3)

    def __unicode__(self):
        return "{0} {1}".format(self.product.product_name, self.status)

somediaapp/forms.py
from django import forms
from django.contrib.auth.models import User

from somediaapp.models import UserProfile


class TweetForm(forms.Form):
    product_name = forms.CharField(max_length=32, disabled=True)
    text = forms.CharField(max_length=140, widget=forms.Textarea(
        attrs={'id': 'text_id', 'placeholder': 'Advert broadcast tweet text'}
    ))


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(max_length=100, widget=forms.PasswordInput)
    password2 = forms.CharField(label="Confirm Password", max_length=100, widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username', )

    # remove help text in the form
    def __init__(self, *args, **kwargs):
        super(UserRegistrationForm, self).__init__(*args, **kwargs)
        for field_name in ['username', 'password', 'password2']:
            self.fields[field_name].help_text = None

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('business_name', )


class LoginForm(forms.Form):
    username = forms.CharField(max_length=32)
    password = forms.CharField(max_length=128, widget=forms.PasswordInput)


class ProductForm(forms.Form):
    product_name = forms.CharField(max_length=32)

somediaapp/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.http.response import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from somediaapp.models import (
    UserProfile,
    Product,
    TweetReply,
)

from somediaapp.forms import (
    ProductForm,
    UserRegistrationForm,
    UserProfileForm,
    TweetForm,
    LoginForm,

)


# print before
import collections
from datetime import datetime
from nltk import metrics  # for defining function precision_recall(.., ..)
from nltk.corpus import stopwords
from nltk.collocations import BigramCollocationFinder
from nltk.metrics import BigramAssocMeasures
from nltk.corpus import movie_reviews
from nltk.corpus import reuters
from nltk.classify import NaiveBayesClassifier
from nltk.classify.util import accuracy  # for later testing the accuracy of the classifier
from nltk.tokenize import word_tokenize  # for word_tokenize method
from nltk.probability import FreqDist, ConditionalFreqDist
from nltk import PorterStemmer


def index(request):
    return render(request, 'index.html', {})


def user_login(request):
    user = request.user
    next_url = request.GET.get('next', '')
    if user.is_authenticated():
        return HttpResponseRedirect('/')
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'], password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    if next_url == '':
                        return HttpResponseRedirect('/')
                    elif next_url:
                        return HttpResponseRedirect(next_url)
            else:

                message = 'Wrong username or password'
                form = LoginForm()
                return render(request, 'login.html', {'form': form, 'message': message, })
    else:
        form = LoginForm()
    return render(request, 'login.html', {'form': form, })


@login_required(login_url='/login/')
def user_logout(request):
    logout(request)
    return render(request, 'logout_then_login.html', {})


def create_account(request):
    if request.method == 'POST':
        profile_form = UserProfileForm(request.POST)
        user_form = UserRegistrationForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save(commit=False)
            user.set_password(user_form.cleaned_data['password2'])
            user.save()
            cd = profile_form.cleaned_data
            company_name = cd['company_name']
            profile = UserProfile.objects.create(
                user=user,
                company_name=company_name
            )
            profile.save()
            message = "account created successfully"
            return HttpResponse(message)
    else:
        user_form = UserRegistrationForm()
        profile_form = UserRegistrationForm()
    return render(request, 'create_account.html', {
        'user_form': user_form,
        'profile_form': profile_form,
        })


@login_required(login_url='/login/')
def add_product(request):
    user = get_object_or_404(User, username=str(request.user))
    profile = get_object_or_404(UserProfile, user=user)

    if request.method == 'POST':
        product_form = ProductForm(request.POST)
        if product_form.is_valid():
            cd = product_form.cleaned_data
            product_name = cd['product_name']

            product = Product.objects.create(
                profile=profile,
                product_name=product_name
            )
            product.save()
            message = "product added successfully"
            return HttpResponse(message)
    else:
        product_form = ProductForm()
    return render(request, 'add_product.html', {'product_form': product_form, })


import tweepy
from django.conf import settings
import json


def get_api():
    consumer_key = str(settings.SOCIAL_AUTH_TWITTER_KEY)
    secret_key = str(settings.SOCIAL_AUTH_TWITTER_SECRET)
    access_token = str(settings.TWITTER_ACCESS_TOKEN)
    access_token_secret = str(settings.TWITTER_ACCESS_TOKEN_SECRET)
    auth = tweepy.OAuthHandler(consumer_key, secret_key)
    auth.set_access_token(access_token, access_token_secret)
    return tweepy.API(auth)


@login_required(login_url='/login/')
def post_tweet(request, product_id=None):
    product = get_object_or_404(Product, id=product_id)
    product_name = str(product.product_name)
    form_initial = {'product_name': product_name}
    if request.method == 'POST':
        tweet_form = TweetForm(request.POST, initial=form_initial)

        if tweet_form.is_valid():
            cd = tweet_form.cleaned_data
            tweet_text = cd['text']
            product.tweet = tweet_text
            try:
                api = get_api()
                status = api.update_status(status=tweet_text)
                # the logic for sending tweet to twitter here
                product.tweet_id = str(status.id_str)

                product.save()

                print str(status.id_str)
                print str(status.in_reply_to_status_id_str)

                message = "broadcast sent successfully"
                return HttpResponse(message)
            except Exception, e:
                return HttpResponse("error occured {0}".format(str(e)))

    else:
        tweet_form = TweetForm(initial=form_initial)
    return render(request, 'send_tweet.html', {'tweet_form': tweet_form})


def high_information_words(labelled_words, score_fn=BigramAssocMeasures.chi_sq, min_score=5):
    word_fd = FreqDist()
    label_word_fd = ConditionalFreqDist()
    for label, words in labelled_words:
        for word in words:
            word_fd.inc(word)
            label_word_fd[label].inc(word)
        n_xx = label_word_fd.N()
        high_info_words = set()
        for label in label_word_fd.conditions():
            n_xi = label_word_fd[label].N()
            word_scores = collections.defaultdict(int)
        for word, n_ii in label_word_fd[label].iteritems():
            n_ix = word_fd[word]
            score = score_fn(n_ii, (n_ix, n_xi), n_xx)
            word_scores[word] = score
        bestwords = [word for word, score in word_scores.iteritems() if score >= min_score]
        high_info_words |= set(bestwords)
    return high_info_words


# classifier

# precision_recall function is one which calculates the precision and recall of the clssifier
def precision_recall(classifier, testfeats):
    refsets = collections.defaultdict(set)
    testsets = collections.defaultdict(set)

    for i, (feats, label) in enumerate(testfeats):
        refsets[label].add(i)
    precisions = {}
    recalls = {}

    for label in classifier.labels():
        precisions[label] = metrics.precision(refsets[label], testsets[label])
        recalls[label] = metrics.recall(refsets[label], testsets[label])
    return precisions, recalls


def bag_of_words(words):
    return dict([(word, True) for word in words])


def bag_of_words_not_in_set(words, badwords):
    # words - this is the original words of the set
    # badwords - are part words but to be discarded(stopwords probably)
    return bag_of_words(set(words) - set(badwords))  # delete badwords from original set of words


def bag_of_non_stopwords(words, stopfile='english'):
    # we are getting rid of english stopwords that are in the the set of words
    badwords = stopwords.words(stopfile)
    return bag_of_words_not_in_set(words, badwords)


def bag_of_bigrams_words(words, score_fn=BigramAssocMeasures.chi_sq, n=200):
    # finds words that often occur togther
    bigram_finder = BigramCollocationFinder.from_words(words)
    bigrams = bigram_finder.nbest(score_fn, n)
    return bag_of_words(words + bigrams)


def label_feats_from_corpus(corp, feature_detector=bag_of_words):
    label_feats = collections.defaultdict(list)
    for label in corp.categories():
        for fileid in corp.fileids(categories=[label]):
            feats = feature_detector(corp.words(fileids=[fileid]))
            label_feats[label].append(feats)
    return label_feats


def split_label_feats(lfeats, split=0.75):
    train_feats = []
    test_feats = []
    for label, feats in lfeats.iteritems():
        cutoff = int(len(feats) * split)
        train_feats.extend([(feat, label) for feat in feats[:cutoff]])
        test_feats.extend([(feat, label) for feat in feats[cutoff:]])
    return train_feats, test_feats

lfeats = label_feats_from_corpus(movie_reviews)
# print lfeats

train_feats, test_feats = split_label_feats(lfeats)

# Define the classifier to analyse the emotion of the input sentence
nb_classifier = NaiveBayesClassifier.train(train_feats)
# nb_classifier.show_most_informative_features()


# Some tests
# def a():
#     while True:
#         print "\nplease enter a sentense to be analysed:"
#         sentence = raw_input('--> ')
#         start = datetime.now().microsecond
#         print "starting to analyse..."
#
#         sent = word_tokenize(sentence)
#         posfeat = bag_of_words(sent)
#
#         result = nb_classifier.classify(posfeat)
#         after = datetime.now().microsecond
#         print "analyse finished..."
#         print "result:", result
#         timeconsuming = after - start
#         print "It takes ", timeconsuming, "milliseconds to analyse the sentence"


def analyse_product_tweet(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    tweet_id = str(product.tweet_id)
    fetched_replies = []
    ips = []
    api = get_api()
    timeline = api.search(q="@Smart_Ad_")
    for tweet in timeline:
        if tweet.in_reply_to_status_id_str:
            print tweet.id_str
            reply = tweet.text
            print reply

somediaapp/templates/add_product.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="jumbotron" style="background-color: #ffffff!important;">
<div class="col col-md-6" style="background-color: #ffffff!important; margin-left: 250px;">
    <h6 class="btn btn-success">Create A product Here</h6>
    <form action="" method="post">
        {{ product_form | crispy }}
        {% csrf_token %}
        <input type="submit" value="Create Product" class="btn btn-primary btn-raised">
    </form>

</div>
</div>
{% endblock %}

somediaapp/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %} Somedia{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- my local css and bootstrap -->
    <link href="{% static 'css/bootstrap.min.css' %} " rel="stylesheet">
    {#    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>#}

    {#    css for material#}
    <link href="{% static 'material/css/bootstrap-material-design.css' %}" rel="stylesheet">
    <link href="{% static 'material/css/ripples.min.css' %}" rel="stylesheet">
    <!-- slider css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/jquery.bxslider.css' %}">
    <!--end of slider css -->


    <!--end of my local -->


    {#    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>#}
    {#    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>#}
    <style type="text/css">
        /* Remove the navbar's default rounded borders and increase the bottom margin */
        .navbar {
            margin-bottom: 50px;
            border-radius: 0;
        }

        .custom {
            background-color: #ffffff;
            background-repeat: no-repeat;
            background-color: transparent;
        }

        /* Remove the jumbotron's default bottom margin */
        .jumbotron {
            margin-bottom: 0;

        }

        /* Add a gray background color and some padding to the footer */
        footer {
            background-color: #f2f2f2 !important;
            padding: 25px;
        }
    </style>
</head>
<body class="custom">
{#<div class="jumbotron">#}
{#    <div class="container text-center">#}
{#        <h1>Nyeri Land Admistration System  </h1>#}
{#    </div>#}
{#</div>#}

<nav class="navbar navbar-primary">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Logo</a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">

            <ul class="nav navbar-nav">

                <li class="active"><a href="#">Home</a></li>
                    <li><a href="{% url 'somedia:my_products' %}">Products</a></li>
                    <li><a href="{% url 'somedia:add_product' %}">Create a product</a></li>
                    <li><a href="#">Product Tweets</a></li>

                <li><a href="#">Product Performance</a></li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Analytics
                        <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li class="dropdown-header">Responses</li>
                        <li><a href="#"> User Product Responses</a></li>


                    </ul>
                </li>

                {% if user.is_authenticated %}
                {% else %}
                    <li><a href="{% url 'somedia:create_account' %}">Create Account</a></li>
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">My Profile
                            <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li class="dropdown-header">MyProfile</li>
                            <li><a href="#">My Products</a></li>
                            <li><a href="#">Product Tweets</a></li>

                        </ul>
                    </li>

                    <li><a href="#"><span class="glyphicon glyphicon-globe"></span>
                        Notifications</a></li>

                    <li><a href="#"><span class="glyphicon glyphicon-user"></span>
                    {{ request.user }}
                    <li><a href="{% url 'somedia:logout' %}"><span class="glyphicon glyphicon-log-out"></span>
                        Logout</a>
                    </li>
                {% else %}
                    <li><a href="{% url 'somedia:login' %}"><span class="glyphicon glyphicon-log-out"></span> Login</a>
                    </li>

                {% endif %}</a></li>

            </ul>
        </div>
    </div>
</nav>


<div class="row">

    {% block content %}

    {% endblock %}
</div>
<footer class="container-fluid text-center">
    Somedia Copyright &copy;2016
</footer>
<!-- Bootstrap Core JavaScript -->
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %} "></script>
<!--material js-->
<script src="{% static 'material/js/material.min.js' %}"></script>
<script src="{% static 'material/js/ripples.min.js' %}"></script>
<script src="{% static 'js/jquery.bxslider.min.js' %}"></script>
<script>
    $(function () {
        $.material.init();
    });
</script>


</body>

somediaapp/templates/create_account.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="col col-md-6">
<div class="jumbotron" style="background-color: #ffffff!important; margin-left: 250px;">
    <form action="#" method="post">

        {{ profile_form |crispy }}
        {{ user_form | crispy }}

        {% csrf_token %}
        <input type="submit" value="create account" class="btn btn-primary btn-raised">
    </form>

</div>
</div>

</div>
{% endblock %}

somediaapp/templates/index.html
{% extends 'base.html' %}

{% block content %}



{% endblock %}

somediaapp/templates/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
<style type="text/css">
    .div-login-form{
        margin-left: 50px !important;
        margin-right: 50px !important;
    }
</style>
{% block content %}
        <div class="row">
           <div class="col col-md-3"></div>
           <div class="">
            <div class="col-col-md-3"></div>
            <div class="div-login-form col col-md-6">
                <p><strong class="btn btn-primary">Login Here</strong></p>
                {% if message %}
                    <div class="alert alert-danger" role="alert">
                        <strong>{{ message }}</strong>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endif %}
             <div class="col-col-md-3" style="margin-left: 25px;">
                <form action="" method="post">
                    {{ form | crispy }}
                    {% csrf_token %}
                    <input type="hidden" name="next" value="{{ next }}" />
                    <input type="submit" value="login" class="col col-md-12 btn btn-success btn-raised">
                </form>
            <div>
            <span>
            &nbsp;&nbsp;Don't have account?<a href="{% url 'somedia:create_account' %}">Create Account</a>
            </span>
           </div>
        </div>
        </div>
    </div>
    </div>
{% endblock %}

somediaapp/templates/logout_then_login.html
{% extends 'base.html' %}

{% block content %}
<div class="col col-md-6">

    <div class="col col-md-4">
    <h6>You are now logged out  <a href="{% url 'somedia:login' %}" class="btn btn-success">login again</a>  </h6>
</div>

</div>
{% endblock %}

somediaapp/templates/map.html
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  <title>Tweet sentiment analysis</title>
  <script src="http://maps.google.com/maps/api/js?sensor=false"></script>
</head>
<body>

  <div id="map" style="width: 500px; height: 400px;"></div>

  <script>
    // Define your locations: HTML content for the info window, latitude, longitude
    var locations = [
      [ 0.3856, 36.9622],
      [0.3956, 37.9622],
      [ 0.4056, 35.9622],
      [ 0.4156, 36.3522],
      [ 0.4256, 37.9622]
    ];

    // Setup the different icons and shadows
    var iconURLPrefix = 'http://maps.google.com/mapfiles/ms/icons/';

    var icons = [
      iconURLPrefix + 'red-dot.png',
      iconURLPrefix + 'green-dot.png',
      iconURLPrefix + 'blue-dot.png',
      iconURLPrefix + 'orange-dot.png',
      iconURLPrefix + 'purple-dot.png',
      iconURLPrefix + 'pink-dot.png',
      iconURLPrefix + 'yellow-dot.png'
    ]
    var iconsLength = icons.length;

    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 10,
      center: new google.maps.LatLng(0.3956, 36.9622),
      mapTypeId: google.maps.MapTypeId.ROADMAP,
      mapTypeControl: false,
      streetViewControl: false,
      panControl: false,
      zoomControlOptions: {
         position: google.maps.ControlPosition.LEFT_BOTTOM
      }
    });

    var infowindow = new google.maps.InfoWindow({
      maxWidth: 160
    });

    var markers = new Array();

    var iconCounter = 0;

    // Add the markers and infowindows to the map
    for (var i = 0; i < locations.length; i++) {
      var marker = new google.maps.Marker({
        position: new google.maps.LatLng(locations[i][1], locations[i][2]),
        map: map,
        icon: icons[iconCounter]
      });

      markers.push(marker);

      google.maps.event.addListener(marker, 'click', (function(marker, i) {
        return function() {
          infowindow.setContent(locations[i][0]);
          infowindow.open(map, marker);
        }
      })(marker, i));

      iconCounter++;
      // We only have a limited number of possible icon colors, so we may have to restart the counter
      if(iconCounter >= iconsLength) {
      	iconCounter = 0;
      }
    }

    function autoCenter() {
      //  Create a new viewpoint bound
      var bounds = new google.maps.LatLngBounds();
      //  Go through each...
      for (var i = 0; i < markers.length; i++) {
				bounds.extend(markers[i].position);
      }
      //  Fit these bounds to the map
      map.fitBounds(bounds);
    }
    autoCenter();
  </script>
</body>
</html>

somediaapp/templates/products.html
{% extends 'base.html' %}

{% block content %}
<div class="jumbotron" style="background-color: #ffffff!important;">
<div class="col col-md-6">
    {% if products %}
        <ul class="list-group">
        {% for product in products %}

            <li class="list-group-item">{{ product.product_name }}
            <a href="{% url 'somedia:post_tweet' product_id=product.id  %}">
                create tweet advert
            </a>
            </li>
        {% endfor %}

        </ul>
    {% else %}
    {% endif %}
</div>

</div>
{% endblock %}

somediaapp/templates/send_tweet.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="col col-md-6" style="background-color: #ffffff!important; margin-left: 250px;">
<div class="jumbotron" style="background-color: #ffffff!important;">
<form action="" method="post">
    {{ tweet_form | crispy }}
    {% csrf_token %}
    <input type="submit" value="send" class="btn btn-primary btn-raised">
</form>
</div>

</div>

{% endblock %}

somediaapp/templates/tweet_analysis.html
{% extends 'base.html' %}

{% block content %}

    <div class="col col-md-6">
    <h6>Analysis for product {{ product }}</h6>
    <table class="col col-md-12">
        <th>
          TWeet Responses
        </th>
        {% for tweet in tweets  %}
          <div class={% if tweet.status == 'pos' %}"alert alert-danger"{% else %}"alert alert-success"{% endif %} role="alert">
            <strong>{{ tweet.reply }}</strong>
          </div>
        {% endfor %}



    </table>
    </div>

{% endblock %}